FROM ubuntu:latest
RUN apt-get upgrade -y && apt-get update -y 
RUN apt-get install -y apt-utils
RUN apt-get update -y
RUN apt-get install -y python3 wget gnupg2
RUN apt-get update -y
# RUN wget -O- http://neuro.debian.net/lists/focal.us-ca.full | tee /etc/apt/sources.list.d/neurodebian.sources.list
# RUN apt-key adv --recv-keys --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9
# use disco instead of focal
RUN wget -O- http://neuro.debian.net/lists/disco.de-m.full | tee /etc/apt/sources.list.d/neurodebian.sources.list
RUN apt-key adv --recv-keys --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9
RUN apt-get update -y
RUN apt-get install -y singularity-container
